### ISSUE TITLE
"unable to resolve dependency tree" error while npm install

### ISSUE THREAD

**Issue by ryota-abe** [IgniteUI/igniteui-angular-wrappers#375]
### Description  
Peer dependency error occurs during installation.

### Steps to reproduce  

1. use latest npm (Probably occurs in version 7 or later)
2. Prepare an Angular15 project. (I used [this](https://codesandbox.io/s/angular-angular))
3. `npm install igniteui-angular-wrappers`

### Result  
Peer dependency error occurs.

### Expected result  
Installed without error

### Attachments  
![image](https://user-images.githubusercontent.com/15438757/207579368-0ab9031d-147b-478b-a2ed-e271730439b3.png)

**Comment by dkamburov** [comment]
@ryota-abe Should be resolved with latest igniteui-angular-wrappers@15.0.0

**Comment by ryota-abe** [comment]
It was not fixed even in 15.0.0.
I see "@angular/common":"^8.0.0" is specified in its peerDependencies.
I believe a value like ">=8.0.0" should be set.

**Comment by dkamburov** [comment]
I see, the package.json of the lib itself wasn't updated, we'll work on that and try having a new version till the end of the next week.
